### ISSUE TITLE
Add Git CLI setup and verification instructions (Windows)

### ISSUE THREAD

**Issue by koushikkothagal** [koushikkothagal/java-backend-bootcamp#7]
Add Windows instructions for:
- Setting up Git CLI
- Testing by cloning this GitHub project

https://github.com/koushikkothagal/java-backend-bootcamp/tree/main/session-02-big-picture#git-and-github

**Comment by vijaysaiy** [comment]
I can take this up, please assign it to me

**Comment by koushikkothagal** [comment]
Done, thanks!
I'll add some feedback to the PR
